# Generated by Django 5.0.1 on 2024-02-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
