# Generated by Django 5.0.1 on 2024-02-06 05:01

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver", "0001_initial"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("submission", "Submission"),
                            ("review", "Review"),
                            ("approval", "Approval"),
                            ("rejection", "Rejection"),
                        ],
                        default="submission",
                        max_length=50,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="driver.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vehicle.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
